// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: torq.proto

package torqrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ForwardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ForwardResponse) Reset() {
	*x = ForwardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_torq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForwardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardResponse) ProtoMessage() {}

func (x *ForwardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_torq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardResponse.ProtoReflect.Descriptor instead.
func (*ForwardResponse) Descriptor() ([]byte, []int) {
	return file_torq_proto_rawDescGZIP(), []int{0}
}

type ForwardsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ForwardsRequest) Reset() {
	*x = ForwardsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_torq_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForwardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardsRequest) ProtoMessage() {}

func (x *ForwardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_torq_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardsRequest.ProtoReflect.Descriptor instead.
func (*ForwardsRequest) Descriptor() ([]byte, []int) {
	return file_torq_proto_rawDescGZIP(), []int{1}
}

var File_torq_proto protoreflect.FileDescriptor

var file_torq_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x74, 0x6f, 0x72, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x74, 0x6f,
	0x72, 0x71, 0x72, 0x70, 0x63, 0x22, 0x11, 0x0a, 0x0f, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x11, 0x0a, 0x0f, 0x46, 0x6f, 0x72, 0x77,
	0x61, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x32, 0x4c, 0x0a, 0x07, 0x74,
	0x6f, 0x72, 0x71, 0x72, 0x70, 0x63, 0x12, 0x41, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x72,
	0x77, 0x61, 0x72, 0x64, 0x73, 0x12, 0x18, 0x2e, 0x74, 0x6f, 0x72, 0x71, 0x72, 0x70, 0x63, 0x2e,
	0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x18, 0x2e, 0x74, 0x6f, 0x72, 0x71, 0x72, 0x70, 0x63, 0x2e, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x6e, 0x63, 0x61, 0x70, 0x69, 0x74, 0x61,
	0x6c, 0x2f, 0x74, 0x6f, 0x72, 0x71, 0x2f, 0x74, 0x6f, 0x72, 0x71, 0x72, 0x70, 0x63, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_torq_proto_rawDescOnce sync.Once
	file_torq_proto_rawDescData = file_torq_proto_rawDesc
)

func file_torq_proto_rawDescGZIP() []byte {
	file_torq_proto_rawDescOnce.Do(func() {
		file_torq_proto_rawDescData = protoimpl.X.CompressGZIP(file_torq_proto_rawDescData)
	})
	return file_torq_proto_rawDescData
}

var file_torq_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_torq_proto_goTypes = []interface{}{
	(*ForwardResponse)(nil), // 0: torqrpc.ForwardResponse
	(*ForwardsRequest)(nil), // 1: torqrpc.ForwardsRequest
}
var file_torq_proto_depIdxs = []int32{
	1, // 0: torqrpc.torqrpc.GetForwards:input_type -> torqrpc.ForwardsRequest
	0, // 1: torqrpc.torqrpc.GetForwards:output_type -> torqrpc.ForwardResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_torq_proto_init() }
func file_torq_proto_init() {
	if File_torq_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_torq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForwardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_torq_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForwardsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_torq_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_torq_proto_goTypes,
		DependencyIndexes: file_torq_proto_depIdxs,
		MessageInfos:      file_torq_proto_msgTypes,
	}.Build()
	File_torq_proto = out.File
	file_torq_proto_rawDesc = nil
	file_torq_proto_goTypes = nil
	file_torq_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TorqrpcClient is the client API for Torqrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TorqrpcClient interface {
	GetForwards(ctx context.Context, in *ForwardsRequest, opts ...grpc.CallOption) (*ForwardResponse, error)
}

type torqrpcClient struct {
	cc grpc.ClientConnInterface
}

func NewTorqrpcClient(cc grpc.ClientConnInterface) TorqrpcClient {
	return &torqrpcClient{cc}
}

func (c *torqrpcClient) GetForwards(ctx context.Context, in *ForwardsRequest, opts ...grpc.CallOption) (*ForwardResponse, error) {
	out := new(ForwardResponse)
	err := c.cc.Invoke(ctx, "/torqrpc.torqrpc/GetForwards", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TorqrpcServer is the server API for Torqrpc service.
type TorqrpcServer interface {
	GetForwards(context.Context, *ForwardsRequest) (*ForwardResponse, error)
}

// UnimplementedTorqrpcServer can be embedded to have forward compatible implementations.
type UnimplementedTorqrpcServer struct {
}

func (*UnimplementedTorqrpcServer) GetForwards(context.Context, *ForwardsRequest) (*ForwardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetForwards not implemented")
}

func RegisterTorqrpcServer(s *grpc.Server, srv TorqrpcServer) {
	s.RegisterService(&_Torqrpc_serviceDesc, srv)
}

func _Torqrpc_GetForwards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TorqrpcServer).GetForwards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/torqrpc.torqrpc/GetForwards",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TorqrpcServer).GetForwards(ctx, req.(*ForwardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Torqrpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "torqrpc.torqrpc",
	HandlerType: (*TorqrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetForwards",
			Handler:    _Torqrpc_GetForwards_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "torq.proto",
}
